const actionTypes = {
  SET_ID: "SET_ID",
  SET_COLUMNS: "SET_COLUMNS",
  SET_DATA: "SET_DATA",
  SET_OPTIONS: "SET_OPTIONS",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_PAGE_SIZE: "SET_PAGE_SIZE",
  SET_SORT_BY: "SET_SORT_BY",
  SET_SORT_DIRECTION: "SET_SORT_DIRECTION",
  SET_FILTER: "SET_FILTER",
};

export default actionTypes;
