const actionTypes = {
  SET_ID: "SET_ID",
  SET_COLUMNS: "SET_COLUMNS",
  SET_DATA: "SET_DATA",
  SET_PAGE_SIZE_OPTIONS: "SET_PAGE_SIZE_OPTIONS",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_TOTAL_PAGES: "SET_TOTAL_PAGES",
  SET_PAGE_SIZE: "SET_PAGE_SIZE",
  SET_SORT_BY: "SET_SORT_BY",
  SET_SORT_DIRECTION: "SET_SORT_DIRECTION",
  SET_FILTER: "SET_FILTER",
  SET_FILTER_RESULTS: "SET_FILTER_RESULTS",
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
}

export default actionTypes
